### PR TITLE
Add commands for inspecting/changing shuffle/repeat state

### PR DESCRIPTION
**Pull request by mdouglass**
Adds the following commands:

```bash
$ sonos info Speaker settings     
{
  "PlayMode": "REPEAT_ONE",
  "RecQualityMode": "NOT_IMPLEMENTED"
}
```

```
$ sonos control Speaker repeatall # sets Speaker to Repeat All
$ sonos control Speaker repeatone # sets Speaker to Repeat One
$ sonos control Speaker repeatoff # sets Speaker to No Repeats
$ sonos control Speaker togglerepeat # cycles Speaker from No Repeats -> Repeat All -> Repeat One -> No Repeats

$ sonos control Speaker shuffleon # sets Speaker to shuffle
$ sonos control Speaker shuffleoff # sets Speaker to not shuffle
$ sonos control Speaker toggleshuffle # toggles Speaker from shuffle to not shuffle
```

### CODE REVIEW

**Comment by mdouglass** [comment]
One minor note - the `PlayMode` definition in the base library has a typo: `SuffleRepeatOne` instead of `ShuffleRepeatOne` (missing `h`). I didn't try to fix that as it would be a breaking change in the main library.

**Comment by mdouglass** [comment]
One other comment - much of the verbosity in this commit stems from PlayMode combining shuffle and repeat states. If you'd prefer, I could make those two separate states in the main library.

**Comment by svrooij** [comment]
Thinking of it, how is `REPEAT_ONE` different from `SHUFFLE_REPEAT_ONE`? Any thoughts @mdouglass? As in, wouldn't both options play the same song over and over?

By the way I'm putting this in the main library, that was a good idea.

**Comment by mdouglass** [comment]
> Thinking of it, how is `REPEAT_ONE` different from `SHUFFLE_REPEAT_ONE`? Any thoughts @mdouglass? As in, wouldn't both options play the same song over and over?
> 
> By the way I'm putting this in the main library, that was a good idea.

I can't think of any way that they are different practically. I think it just reflects that there are two buttons in the native Sonos UI and so you can have Shuffle and Repeat One set or you can have Shuffle and Repeat None set. Its awkward, but probably safer to stay with the way the native UI thinks of it.

If you make the changes in the main library, then I can redo this PR after that lands.

**Comment by svrooij** [comment]
You can use this release, https://www.npmjs.com/package/@svrooij/sonos/v/2.6.0-beta.1 for the cli it doesn't matter if you use a beta of the main lib. The changes in the main lib should make this pr a lot easier.

**Comment by mdouglass** [comment]
Updated to use the new release, seems to work well for me.

**Comment by svrooij** [comment]
Can you run `npm run readme` to also update the readme? Then I'm good with the PR.

**Comment by mdouglass** [comment]
> Can you run `npm run readme` to also update the readme? Then I'm good with the PR.

Should be all set now.

**Comment by svrooij** [comment]
@mdouglass for some reason it did not see your changes as something to create a new release for. I manually triggered a new build. So now, finally, your change is live.

**Comment by mdouglass** [comment]
Excellent thank you!

**Pull request merged**
