### PR TITLE
Various fixes/changes

### PR DESCRIPTION
**Pull request by mdouglass**
These are a series of mostly unrelated changes to sonos-cli to fix/address issues I had when trying it with my Play:1. I'm happy to break these into indvidual PRs if you only want to upstream some (or none) of them.

- [Update to 2.4.1 release of @svrooij/sonos](https://github.com/svrooij/sonos-cli/commit/b9797d7af4d1543a3b28b163a72fde790c986ae1) 
- [Fixed control command to properly use command arg](https://github.com/svrooij/sonos-cli/commit/3a2b90f6771859a713d1c02457f9a5797b5b677b)
- [Add control commands for manipulating mute state](https://github.com/svrooij/sonos-cli/commit/1defa3eca181cb3a1aa27412bf75e2ae16d29ffa)
- [Change play to use SwitchToQueue](https://github.com/svrooij/sonos-cli/commit/40bff7b420e6938b3f68636edea282890dde5e58)
- [Add queue clear command](https://github.com/svrooij/sonos-cli/commit/adaabc7c85254a915b0907a433ecb82573191e6b)

### CODE REVIEW

**Comment by svrooij** [comment]
Wait what, someone is actually using this cli? How awesome!

I’m on my iPad at the moment. So I cannot go into great detail, reviewing your pr. But at first glance it looks good.

**Comment by mdouglass** [comment]
Yeah, turned out to be pretty handy. Wanted something to trigger from my Stream Deck and was going to use the node api directly, but most of what I wanted was already in here :)

**Comment by svrooij** [comment]
Maybe even document the stream deck integration?

**Comment by mdouglass** [comment]
Not sure the integration is all that useful. I use https://github.com/timothycrosley/streamdeck-ui/ and that can just execute a command line tool when a button is pressed. I've got a very small bash script that calls out to sonos-cli for different buttons:
```bash
#! /bin/bash

export PATH=~/bin:~/.nvm/versions/node/v16.13.1/bin:$PATH

play-album() {
  stop
  sonos play Office apple:album:$1
  sonos control Office play
}

play-library-playlist() {
  stop
  sonos play Office apple:libraryplaylist:$1
  sonos control Office play
}

stop() {
  sonos queue Office clear
  sonos control Office stop
}

case $1 in
  play-album)
    play-album $2
    ;;

  play-library-playlist)
    play-library-playlist $2
    ;;

  *)
    sonos $*
    ;;
esac
```

**Comment by svrooij** [comment]
I'm so sorry I broke your branch 🤗 migrating to a new version of Oclif wasn't a good idea. I also fixed it https://github.com/svrooij/sonos-cli/tree/mdouglass/master

can you test that branch and do you agree that I use that version going forward? You will be in the commits anyway because I left your commits in that branch

**Comment by mdouglass** [comment]
Definitely makes sense to go ahead and upgrade.  I'll test my branch again this evening.

**Comment by svrooij** [comment]
@mdouglass could you try this branch: https://github.com/svrooij/sonos-cli/tree/mdouglass/master github pushed the changes to my repo instead of yours. I'm no git hero 😞 

If you confirm everything still works I'll accept #19 and that will release a new version for everybody

**Pull request closed without merging**
